config/routes.rb
Telecentro::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :servicios

  resources :personas

  resources :venta

   root :to => 'welcome#index'

end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
  has_many :venta
  alias_attribute :name, :nombre
end

app/controllers/servicios_controller.rb
class ServiciosController < ApplicationController
  # GET /servicios
  # GET /servicios.json
  def index
    @servicios = Servicio.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @servicios }
    end
  end

  # GET /servicios/1
  # GET /servicios/1.json
  def show
    @servicio = Servicio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @servicio }
    end
  end

  # GET /servicios/new
  # GET /servicios/new.json
  def new
    @servicio = Servicio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @servicio }
    end
  end

  # GET /servicios/1/edit
  def edit
    @servicio = Servicio.find(params[:id])
  end

  # POST /servicios
  # POST /servicios.json
  def create
    @servicio = Servicio.new(params[:servicio])

    respond_to do |format|
      if @servicio.save
        format.html { redirect_to @servicio, :notice => 'Servicio was successfully created.' }
        format.json { render :json => @servicio, :status => :created, :location => @servicio }
      else
        format.html { render :action => "new" }
        format.json { render :json => @servicio.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /servicios/1
  # PUT /servicios/1.json
  def update
    @servicio = Servicio.find(params[:id])

    respond_to do |format|
      if @servicio.update_attributes(params[:servicio])
        format.html { redirect_to @servicio, :notice => 'Servicio was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @servicio.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /servicios/1
  # DELETE /servicios/1.json
  def destroy
    @servicio = Servicio.find(params[:id])
    @servicio.destroy

    respond_to do |format|
      format.html { redirect_to servicios_url }
      format.json { head :ok }
    end
  end
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/views/servicios/_form.html.erb
<%= form_for(@servicio) do |f| %>
  <% if @servicio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@servicio.errors.count, "error") %> prohibited this servicio from being saved:</h2>

      <ul>
      <% @servicio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :precio %><br />
    <%= f.text_field :precio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/servicios/edit.html.erb
<h1>Editing servicio</h1>

<%= render 'form' %>

<%= link_to 'Show', @servicio %> |
<%= link_to 'Back', servicios_path %>

app/views/servicios/index.html.erb
<h1>Listing servicios</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Precio</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @servicios.each do |servicio| %>
  <tr>
    <td><%= servicio.nombre %></td>
    <td><%= servicio.precio %></td>
    <td><%= link_to 'Show', servicio %></td>
    <td><%= link_to 'Edit', edit_servicio_path(servicio) %></td>
    <td><%= link_to 'Destroy', servicio, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Servicio', new_servicio_path %>

app/views/servicios/new.html.erb
<h1>New servicio</h1>

<%= render 'form' %>

<%= link_to 'Back', servicios_path %>

app/views/servicios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @servicio.nombre %>
</p>

<p>
  <b>Precio:</b>
  <%= @servicio.precio %>
</p>


<%= link_to 'Edit', edit_servicio_path(@servicio) %> |
<%= link_to 'Back', servicios_path %>