config/routes.rb
Telecentro::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :servicios

  resources :personas

  resources :venta

   root :to => 'welcome#index'

end

app/controllers/venta_controller.rb
class VentaController < ApplicationController
  # GET /venta
  # GET /venta.json
  def index
    @venta = Ventum.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @venta }
    end
  end

  # GET /venta/1
  # GET /venta/1.json
  def show
    @ventum = Ventum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @ventum }
    end
  end

  # GET /venta/new
  # GET /venta/new.json
  def new
    @ventum = Ventum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @ventum }
    end
  end

  # GET /venta/1/edit
  def edit
    @ventum = Ventum.find(params[:id])
  end

  # POST /venta
  # POST /venta.json
  def create
    @ventum = Ventum.new(params[:ventum])

    respond_to do |format|
      if @ventum.save
        format.html { redirect_to @ventum, :notice => 'Ventum was successfully created.' }
        format.json { render :json => @ventum, :status => :created, :location => @ventum }
      else
        format.html { render :action => "new" }
        format.json { render :json => @ventum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /venta/1
  # PUT /venta/1.json
  def update
    @ventum = Ventum.find(params[:id])

    respond_to do |format|
      if @ventum.update_attributes(params[:ventum])
        format.html { redirect_to @ventum, :notice => 'Ventum was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @ventum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /venta/1
  # DELETE /venta/1.json
  def destroy
    @ventum = Ventum.find(params[:id])
    @ventum.destroy

    respond_to do |format|
      format.html { redirect_to venta_url }
      format.json { head :ok }
    end
  end
end

app/helpers/venta_helper.rb
module VentaHelper
end

app/views/venta/_form.html.erb
<%= form_for(@ventum) do |f| %>
  <% if @ventum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ventum.errors.count, "error") %> prohibited this ventum from being saved:</h2>

      <ul>
      <% @ventum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :persona_id %><br />
    <%= f.number_field :persona_id %>
  </div>
  <div class="field">
    <%= f.label :servicio_id %><br />
    <%= f.number_field :servicio_id %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br />
    <%= f.text_field :cantidad %>
  </div>
  <div class="field">
    <%= f.label :monto %><br />
    <%= f.text_field :monto %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br />
    <%= f.date_select :fecha %>
  </div>
  <div class="field">
    <%= f.label :hora %><br />
    <%= f.time_select :hora %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/venta/edit.html.erb
<h1>Editing ventum</h1>

<%= render 'form' %>

<%= link_to 'Show', @ventum %> |
<%= link_to 'Back', venta_path %>

app/views/venta/index.html.erb
<h1>Listing venta</h1>

<table>
  <tr>
    <th>Persona</th>
    <th>Servicio</th>
    <th>Cantidad</th>
    <th>Monto</th>
    <th>Fecha</th>
    <th>Hora</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @venta.each do |ventum| %>
  <tr>
    <td><%= ventum.persona %></td>
    <td><%= ventum.servicio %></td>
    <td><%= ventum.cantidad %></td>
    <td><%= ventum.monto %></td>
    <td><%= ventum.fecha %></td>
    <td><%= ventum.hora %></td>
    <td><%= link_to 'Show', ventum %></td>
    <td><%= link_to 'Edit', edit_ventum_path(ventum) %></td>
    <td><%= link_to 'Destroy', ventum, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ventum', new_ventum_path %>

app/views/venta/new.html.erb
<h1>New ventum</h1>

<%= render 'form' %>

<%= link_to 'Back', venta_path %>

app/views/venta/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Persona:</b>
  <%= @ventum.persona_id %>
</p>

<p>
  <b>Servicio:</b>
  <%= @ventum.servicio_id %>
</p>

<p>
  <b>Cantidad:</b>
  <%= @ventum.cantidad %>
</p>

<p>
  <b>Monto:</b>
  <%= @ventum.monto %>
</p>

<p>
  <b>Fecha:</b>
  <%= @ventum.fecha %>
</p>

<p>
  <b>Hora:</b>
  <%= @ventum.hora %>
</p>


<%= link_to 'Edit', edit_ventum_path(@ventum) %> |
<%= link_to 'Back', venta_path %>