config/routes.rb
Telecentro::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :servicios

  resources :personas

  resources :venta

   root :to => 'welcome#index'

end

app/models/persona.rb
class Persona < ActiveRecord::Base
  has_many :venta
  belongs_to :tele_operador
  has_one :bono
  before_save do |persona|
    persona.name ="#{persona.nombre} #{persona.apellido1} #{persona.apellido2}"
  end
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  # GET /personas
  # GET /personas.json
  def index
    @personas = Persona.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @personas }
    end
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
    @persona = Persona.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @persona }
    end
  end

  # GET /personas/new
  # GET /personas/new.json
  def new
    @persona = Persona.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @persona }
    end
  end

  # GET /personas/1/edit
  def edit
    @persona = Persona.find(params[:id])
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(params[:persona])

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, :notice => 'Persona was successfully created.' }
        format.json { render :json => @persona, :status => :created, :location => @persona }
      else
        format.html { render :action => "new" }
        format.json { render :json => @persona.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /personas/1
  # PUT /personas/1.json
  def update
    @persona = Persona.find(params[:id])

    respond_to do |format|
      if @persona.update_attributes(params[:persona])
        format.html { redirect_to @persona, :notice => 'Persona was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @persona.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona = Persona.find(params[:id])
    @persona.destroy

    respond_to do |format|
      format.html { redirect_to personas_url }
      format.json { head :ok }
    end
  end
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/views/personas/_form.html.erb
<%= form_for(@persona) do |f| %>
  <% if @persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

      <ul>
      <% @persona.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido1 %><br />
    <%= f.text_field :apellido1 %>
  </div>
  <div class="field">
    <%= f.label :apellido2 %><br />
    <%= f.text_field :apellido2 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/personas/edit.html.erb
<h1>Editing persona</h1>

<%= render 'form' %>

<%= link_to 'Show', @persona %> |
<%= link_to 'Back', personas_path %>

app/views/personas/index.html.erb
<h1>Listing personas</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Apellido1</th>
    <th>Apellido2</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @personas.each do |persona| %>
  <tr>
    <td><%= persona.nombre %></td>
    <td><%= persona.apellido1 %></td>
    <td><%= persona.apellido2 %></td>
    <td><%= link_to 'Show', persona %></td>
    <td><%= link_to 'Edit', edit_persona_path(persona) %></td>
    <td><%= link_to 'Destroy', persona, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Persona', new_persona_path %>

app/views/personas/new.html.erb
<h1>New persona</h1>

<%= render 'form' %>

<%= link_to 'Back', personas_path %>

app/views/personas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @persona.nombre %>
</p>

<p>
  <b>Apellido1:</b>
  <%= @persona.apellido1 %>
</p>

<p>
  <b>Apellido2:</b>
  <%= @persona.apellido2 %>
</p>


<%= link_to 'Edit', edit_persona_path(@persona) %> |
<%= link_to 'Back', personas_path %>